# Generated by Django 5.1.6 on 2025-03-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EarlyAccessForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("has_paid", models.BooleanField(default=False)),
                ("product_id", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "stripe_checkout_session_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=100, null=True
                    ),
                ),
                ("payment_date", models.DateTimeField(blank=True, null=True)),
                (
                    "email_verification_token",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("token_created_at", models.DateTimeField(blank=True, null=True)),
                ("is_email_verified", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Early Access Form",
                "verbose_name_plural": "Early Access Forms",
                "ordering": ["-created_at"],
            },
        ),
    ]
