# Generated by Django 5.1.6 on 2025-03-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("earlyaccess_form", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="earlyaccessform",
            name="referral_id",
            field=models.CharField(
                blank=True, help_text="Rewardful referral ID", max_length=100, null=True
            ),
        ),
    ]
