# Generated by Django 5.1.6 on 2025-03-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("earlyaccess_form", "0002_earlyaccessform_referral_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="earlyaccessform",
            name="payment_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
