# Generated by Django 5.1.6 on 2025-03-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatsession",
            name="workflow",
        ),
        migrations.AddField(
            model_name="chatsession",
            name="workflow_data",
            field=models.JSONField(default=dict),
        ),
    ]
