# Generated by Django 5.1.6 on 2025-03-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_remove_chatsession_workflow_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="chat_type",
            field=models.CharField(
                choices=[("workflow", "Workflow"), ("general", "General")],
                default="workflow",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="workflow_id",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
