# Generated by Django 5.1.6 on 2025-04-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_chatsession_chat_type_chatsession_workflow_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatsession",
            name="chat_type",
            field=models.CharField(
                choices=[("workflow", "workflow"), ("general", "general")],
                default="workflow",
                max_length=255,
            ),
        ),
    ]
