# Generated by Django 5.1.6 on 2025-04-07 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djstripe", "0014_2_9a"),
        ("subscription", "0002_usersubscription_referral_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionproduct",
            name="stripe_product_id",
        ),
        migrations.AddField(
            model_name="subscriptionproduct",
            name="stripe_product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscription_products",
                to="djstripe.product",
                to_field="id",
            ),
        ),
    ]
