# Generated by Django 5.1.6 on 2025-03-11 16:01

import django.db.models.deletion
import uuid
import workflow.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        null=True,
                        validators=[workflow.models.validate_metadata],
                    ),
                ),
                ("prompt", models.TextField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("type", models.CharField(blank=True, max_length=50, null=True)),
                ("position_x", models.IntegerField(blank=True, null=True)),
                ("position_y", models.IntegerField(blank=True, null=True)),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        null=True,
                        validators=[workflow.models.validate_node_data],
                    ),
                ),
                ("source_handles", models.JSONField(blank=True, null=True)),
                ("dragging", models.BooleanField(default=False)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("width", models.IntegerField(blank=True, null=True)),
                ("position_absolute_x", models.IntegerField(blank=True, null=True)),
                ("position_absolute_y", models.IntegerField(blank=True, null=True)),
                ("selected", models.BooleanField(default=False)),
                (
                    "workflow",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="workflow.workflow",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Edge",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=100, null=True)),
                ("target", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "source_handle",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "workflow",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edges",
                        to="workflow.workflow",
                    ),
                ),
            ],
        ),
    ]
