# Generated by Django 5.1.6 on 2025-03-12 10:43

from django.db import migrations, models
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="user_query",
            field=models.TextField(blank=True, null=True),
        ),
        TrigramExtension(),
    ]
