"""Django settings for AI Recommendation Platform.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from envs.env_loader import env_loader

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = "management/"

FRONTEND_URL = env_loader.frontend_url
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env_loader.secret_key
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# CSRF settings
CSRF_TRUSTED_ORIGINS = [
    # Add your trusted origins here
]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "authentication",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework.authtoken",
    "corsheaders",
    "drf_spectacular",
    "django.contrib.sites",
    "onboarding_questions",
    "prompt_optimization",
    "workflow",
    "guest_user",
    "djstripe",
    "subscription",
    "forms.earlyaccess_form",
    "forms.newslettersubscriber_form",
    "forms.submitresource_form",
    "forms.shareideas_form",
    "forms.invitefriends_form",
    "management.search",
    "management.tools.apps.ToolsConfig",
    "rest_framework_simplejwt.token_blacklist",
    "management.chat",
    "management.contractor",
    "ai_tool_recommender",
    "consultant_recommender",
    "management.tool_scraping",
    "storages",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # Must be before CommonMiddleware!
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "configurations.urls"


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "configurations.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env_loader.database_name,
        "USER": env_loader.database_user,
        "PASSWORD": env_loader.database_password,
        "HOST": env_loader.database_host,
        "PORT": env_loader.database_port,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"

# Define the directory where static files will be collected
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Additional locations of static files
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# Media files
MEDIA_URL = "/media/"
# Save files to project root /media/ (not management/media/)
# In Docker: /app/media (one level up from /app/management)
# Locally: project_root/media (one level up from management/)
_settings_dir = Path(__file__).resolve().parent.parent  # management/
_project_root = _settings_dir.parent  # project root (one level up)
MEDIA_ROOT = str(_project_root / "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "management.authentication.authentication.CustomJWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 5,
}


AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",  # Default backend
    "authentication.backends.EmailOrUsernameModelBackend",  # Custom backend
]

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

AUTH_USER_MODEL = "authentication.CustomUser"

SITE_ID = 1

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(int(env_loader.jwt_authentication_timeout)),
    "REFRESH_TOKEN_LIFETIME": timedelta(int(env_loader.jwt_authentication_timeout)),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "JTI_CLAIM": "jti",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",
    "UPDATE_LAST_LOGIN": False,
}

SPECTACULAR_SETTINGS = {
    "TITLE": "AI Recommendation API",
    "DESCRIPTION": "AI Tool and Consultant Recommendation Platform API",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SERVE_PERMISSIONS": ["rest_framework.permissions.AllowAny"],
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,
        "displayOperationId": True,
    },
    "SECURITY": [
        {
            "Bearer": [],
        }
    ],
    "SECURITY_DEFINITIONS": {
        "Bearer": {
            "type": "http",
            "scheme": "bearer",
            "bearerFormat": "JWT",
        }
    },
    "PREPROCESSING_HOOKS": ["drf_spectacular.hooks.preprocess_exclude_path_format"],
}

# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = env_loader.email_host
# EMAIL_HOST_USER = env_loader.email_host_user
# EMAIL_HOST_PASSWORD = env_loader.email_host_password
# EMAIL_PORT = env_loader.email_port
# EMAIL_USE_TLS = True
# EMAIL_USE_SSL = False

STRIPE_SECRET_KEY = env_loader.stripe_secret_key
STRIPE_PUBLISHABLE_KEY = env_loader.stripe_publishable_key
STRIPE_WEBHOOK_SECRET = env_loader.stripe_webhook_secret

# dj-stripe settings
STRIPE_LIVE_MODE = False  # Change to True in production
DJSTRIPE_WEBHOOK_SECRET = env_loader.stripe_webhook_secret
DJSTRIPE_USE_NATIVE_JSONFIELD = True
DJSTRIPE_FOREIGN_KEY_TO_FIELD = "id"

# Add these Stripe API key settings
# STRIPE_TEST_SECRET_KEY = env_loader.stripe_secret_key
STRIPE_TEST_PUBLIC_KEY = env_loader.stripe_publishable_key
# STRIPE_LIVE_SECRET_KEY = ""  # Add your live key when going to production
STRIPE_LIVE_PUBLIC_KEY = ""  # Add your live key when going to production

# frontend url
FRONTEND_URL = env_loader.frontend_url

# base url
BASE_URL = env_loader.base_url

# FastAPI Service Configuration
FASTAPI_SERVICE_URL = (
    env_loader.fastapi_service_url or "http://0.0.0.0:12000/ai_tool_recommender"
)


ENV_TYPE = os.getenv("ENV", "development")
if ENV_TYPE == "development":
    DEBUG = True
else:
    DEBUG = False

# AWS S3 settings
AWS_ACCESS_KEY_ID = env_loader.access_key
AWS_SECRET_ACCESS_KEY = env_loader.secret_access_key
AWS_STORAGE_BUCKET_NAME = env_loader.bucket_name
AWS_S3_REGION_NAME = os.getenv("AWS_REGION", "eu-north-1")
AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"
AWS_S3_FILE_OVERWRITE = False
AWS_QUERYSTRING_AUTH = False

# S3 Storage Configuration
DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
# STATICFILES_STORAGE = "storages.backends.s3boto3.S3Boto3Storage" # Uncomment if static on S3

# Celery Configuration
CELERY_BROKER_URL = (
    os.getenv("REDIS_URL")
    or f"redis://{os.getenv('REDIS_HOST', 'redis')}:{os.getenv('REDIS_PORT', '6379')}/{os.getenv('REDIS_DB', '0')}"
)
CELERY_RESULT_BACKEND = CELERY_BROKER_URL

# SSL Configuration for Redis (Only for Upstash/External Redis with SSL)
# Only set SSL parameters if we're actually using a rediss:// URL or TLS is explicitly enabled
redis_url = os.getenv("REDIS_URL", "")
redis_tls = os.getenv("REDIS_TLS", "false").lower() == "true"

# Only configure SSL if using rediss:// scheme (not for local redis://)
if redis_url.startswith("rediss://") or (
    redis_tls and not redis_url.startswith("redis://")
):
    # CERT_NONE is appropriate for Upstash Redis (self-signed certificates)
    # Must use ssl.CERT_NONE constant, not None (Celery requires this)
    CELERY_BROKER_USE_SSL = {
        "ssl_cert_reqs": None,  # Use SSL constant, not None
        "ssl_ca_certs": None,
        "ssl_certfile": None,
        "ssl_keyfile": None,
        "ssl_check_hostname": False,
    }
    CELERY_REDIS_BACKEND_USE_SSL = {
        "ssl_cert_reqs": None,  # Use SSL constant, not None
        "ssl_ca_certs": None,
        "ssl_certfile": None,
        "ssl_keyfile": None,
        "ssl_check_hostname": False,
    }

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutes
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_ACKS_LATE = True

# Tool Scraping Configuration
APIFY_API_KEY = os.getenv("APIFY_API_KEY")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
SCRAPING_DELAY_SECONDS = int(os.getenv("SCRAPING_DELAY_SECONDS", "2"))
PINECONE_API_KEY = os.getenv("PINECONE_API_KEY")
PINECONE_TOOL_INDEX = os.getenv("PINECONE_TOOL_INDEX", "ai-tools-index")
PINECONE_NAMESPACE = os.getenv("PINECONE_NAMESPACE", "")

# Claude API Configuration (for AI Tool Recommender workflow generation)
CLAUDE_API_KEY = os.getenv("CLAUDE_API_KEY")
CLAUDE_MODEL = os.getenv("CLAUDE_MODEL", "claude-sonnet-4-20250514")
