# Generated by Django 5.1.6 on 2025-03-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_emailverificationtoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
