# Generated by Django 5.1.6 on 2025-03-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_alter_customuser_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="login_counter",
            field=models.IntegerField(default=0),
        ),
    ]
