# Generated by Django 5.1.6 on 2025-03-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0005_customuser_login_counter"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_early_access_user",
            field=models.BooleanField(default=False),
        ),
    ]
