# Generated by Django 5.1.6 on 2025-03-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0006_customuser_is_early_access_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "Normal User"),
                    ("contractor", "Contractor"),
                    ("admin", "Admin"),
                ],
                default="user",
                help_text="User's role in the system",
                max_length=20,
            ),
        ),
    ]
