# Generated by Django 5.1.6 on 2025-03-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0008_customuser_about_customuser_apps_included_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="trial_searches",
            field=models.IntegerField(
                default=10,
                help_text="Number of free trial searches available to the user",
            ),
        ),
    ]
