# Generated by Django 5.1.6 on 2025-03-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0009_customuser_trial_searches"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="trial_searches_total",
            field=models.IntegerField(
                default=10,
                help_text="Total number of free trial searches available to the user",
            ),
        ),
    ]
