# Generated by Django 5.1.6 on 2025-04-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0010_customuser_trial_searches_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="trial_searches",
            field=models.IntegerField(
                default=0,
                help_text="Number of free trial searches available to the user",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="trial_searches_total",
            field=models.IntegerField(
                default=0,
                help_text="Total number of free trial searches available to the user",
            ),
        ),
    ]
