# Generated by Django 5.1.6 on 2025-04-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0011_alter_customuser_trial_searches_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_picture",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
