# Generated by Django 5.1.6 on 2025-04-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0012_customuser_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_picture_source",
            field=models.CharField(
                choices=[
                    ("google", "Google"),
                    ("manual", "Manual Upload"),
                    ("default", "Default"),
                ],
                default="default",
                max_length=10,
            ),
        ),
    ]
