# Generated by Django 5.2.7 on 2025-10-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0013_customuser_profile_picture_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture_source",
            field=models.CharField(
                choices=[
                    ("google", "Google"),
                    ("linkedin", "LinkedIn"),
                    ("manual", "Manual Upload"),
                    ("default", "Default"),
                ],
                default="default",
                max_length=10,
            ),
        ),
    ]
