# Generated by Django 5.1.6 on 2025-03-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GuestUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("no_of_requests", models.IntegerField(default=0)),
                (
                    "refresh_token",
                    models.CharField(blank=True, max_length=800, null=True),
                ),
                (
                    "access_token",
                    models.CharField(blank=True, max_length=800, null=True),
                ),
                ("workflow_count", models.IntegerField(default=0)),
            ],
        ),
    ]
