# Generated by Django 5.1.6 on 2025-03-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SubmitResourceForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(verbose_name="Resource URL")),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Resource Title"),
                ),
                ("description", models.TextField(verbose_name="Resource Description")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Submit Resource Form",
                "verbose_name_plural": "Submit Resource Forms",
                "ordering": ["-created_at"],
            },
        ),
    ]
