# Generated by Django 5.1.6 on 2025-03-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchusagelog",
            name="search_type",
            field=models.CharField(
                choices=[
                    ("trial", "Trial Search"),
                    ("subscription", "Subscription Search"),
                ],
                default="trial",
                help_text="Whether this search used trial credits or subscription credits",
                max_length=20,
            ),
        ),
    ]
