# Generated by Django 5.1.6 on 2025-03-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShareIdeasForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("feedback", models.TextField(verbose_name="Feedback/Ideas")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Share Ideas Form",
                "verbose_name_plural": "Share Ideas Forms",
                "ordering": ["-created_at"],
            },
        ),
    ]
