# Generated by Django 5.1.6 on 2025-10-03 12:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIToolSearchLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("query", models.TextField(help_text="Original search query")),
                (
                    "refined_query",
                    models.TextField(
                        blank=True, help_text="Refined query after processing"
                    ),
                ),
                ("max_results", models.IntegerField(default=10)),
                ("include_pinecone", models.BooleanField(default=True)),
                ("include_internet", models.BooleanField(default=True)),
                ("pinecone_results_count", models.IntegerField(default=0)),
                ("internet_results_count", models.IntegerField(default=0)),
                ("total_results_count", models.IntegerField(default=0)),
                ("response_time_ms", models.FloatField(blank=True, null=True)),
                ("cache_hit", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("error", "Error"),
                            ("timeout", "Timeout"),
                        ],
                        default="success",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_tool_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_tool_search_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BackgroundTask",
            fields=[
                (
                    "task_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("discovery", "Tool Discovery"),
                            ("scraping", "URL Scraping"),
                            ("pinecone_update", "Pinecone Update"),
                            ("cache_cleanup", "Cache Cleanup"),
                            ("workflow_gen", "Workflow Generation"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("params", models.JSONField(default=dict)),
                ("result", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "background_tasks",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="background__status_47caec_idx",
                    ),
                    models.Index(
                        fields=["task_type", "status"],
                        name="background__task_ty_d0faba_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DiscoveredTool",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("category", models.CharField(blank=True, max_length=100)),
                ("features", models.TextField(blank=True)),
                ("tags", models.CharField(blank=True, max_length=500)),
                ("website", models.URLField(max_length=500)),
                ("twitter", models.URLField(blank=True, max_length=500)),
                ("facebook", models.URLField(blank=True, max_length=500)),
                ("linkedin", models.URLField(blank=True, max_length=500)),
                ("instagram", models.URLField(blank=True, max_length=500)),
                ("youtube", models.URLField(blank=True, max_length=500)),
                ("tiktok", models.URLField(blank=True, max_length=500)),
                ("price_from", models.CharField(blank=True, max_length=50)),
                ("price_to", models.CharField(blank=True, max_length=50)),
                ("pricing_model", models.CharField(blank=True, max_length=100)),
                ("source", models.CharField(default="internet", max_length=50)),
                (
                    "discovery_query",
                    models.TextField(help_text="Query that discovered this tool"),
                ),
                ("relevance_score", models.FloatField(default=0.0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("added", "Added to Main Database"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("added_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tool",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discovered_from",
                        to="tools.tool",
                    ),
                ),
            ],
            options={
                "db_table": "discovered_tools",
                "ordering": ["-discovered_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowGeneration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("query", models.TextField(help_text="Original query for workflow")),
                (
                    "workflow_data",
                    models.JSONField(
                        help_text="Complete workflow JSON with nodes and edges"
                    ),
                ),
                ("tools_count", models.IntegerField(default=0)),
                (
                    "generation_method",
                    models.CharField(
                        choices=[
                            ("llm", "LLM Generated"),
                            ("fallback", "Fallback Template"),
                        ],
                        default="llm",
                        max_length=50,
                    ),
                ),
                ("generation_time_ms", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "search_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflows",
                        to="ai_tool_recommender.aitoolsearchlog",
                    ),
                ),
                (
                    "tools",
                    models.ManyToManyField(
                        blank=True, related_name="workflows", to="tools.tool"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_generations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "workflow_generations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="aitoolsearchlog",
            index=models.Index(
                fields=["user", "created_at"], name="ai_tool_sea_user_id_99dd67_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aitoolsearchlog",
            index=models.Index(
                fields=["status", "created_at"], name="ai_tool_sea_status_06b95f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discoveredtool",
            index=models.Index(
                fields=["status", "discovered_at"], name="discovered__status_0ffe51_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discoveredtool",
            index=models.Index(
                fields=["website"], name="discovered__website_3a8e56_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowgeneration",
            index=models.Index(
                fields=["user", "created_at"], name="workflow_ge_user_id_cfa90b_idx"
            ),
        ),
    ]
