# Generated by Django 5.2.7 on 2025-10-07 13:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_tool_recommender", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ToolComparison",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "original_tool_node_id",
                    models.CharField(help_text="Node ID in workflow", max_length=100),
                ),
                (
                    "original_tool_data",
                    models.JSONField(help_text="Original tool data from workflow node"),
                ),
                (
                    "comparison_query",
                    models.TextField(help_text="Query used to find alternative tools"),
                ),
                (
                    "alternative_tools",
                    models.JSONField(
                        default=list, help_text="List of alternative tools found"
                    ),
                ),
                ("total_alternatives_found", models.IntegerField(default=0)),
                ("search_time_ms", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_comparisons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_comparisons",
                        to="ai_tool_recommender.workflowgeneration",
                    ),
                ),
            ],
            options={
                "db_table": "tool_comparisons",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="tool_compar_user_id_b5d146_idx",
                    ),
                    models.Index(
                        fields=["workflow", "created_at"],
                        name="tool_compar_workflo_797a1b_idx",
                    ),
                ],
            },
        ),
    ]
