# Generated by Django 5.2.7 on 2025-10-14 12:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_tool_recommender", "0002_toolcomparison"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "original_query",
                    models.TextField(
                        help_text="Initial user query that started the conversation"
                    ),
                ),
                (
                    "chat_history",
                    models.JSONField(
                        default=list, help_text="Complete conversation history"
                    ),
                ),
                (
                    "current_context",
                    models.JSONField(
                        default=dict, help_text="Current conversation context and state"
                    ),
                ),
                (
                    "workflow_nodes",
                    models.JSONField(
                        default=list, help_text="Nodes added during conversation"
                    ),
                ),
                (
                    "workflow_edges",
                    models.JSONField(
                        default=list, help_text="Edges/connections between nodes"
                    ),
                ),
                (
                    "suggested_tools",
                    models.JSONField(
                        default=list, help_text="Tools suggested during conversation"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "conversation_sessions",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_message", models.TextField(help_text="User's message")),
                ("ai_response", models.TextField(help_text="AI's response")),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("chat", "General Chat"),
                            ("tool_suggestion", "Tool Suggestion"),
                            ("workflow_building", "Workflow Building"),
                            ("tool_exploration", "Tool Exploration"),
                            ("workflow_generation", "Workflow Generation"),
                        ],
                        default="chat",
                        help_text="Type of conversation message",
                        max_length=50,
                    ),
                ),
                (
                    "tools_mentioned",
                    models.JSONField(
                        default=list, help_text="Tools mentioned in this message"
                    ),
                ),
                (
                    "workflow_changes",
                    models.JSONField(
                        default=dict, help_text="Changes made to workflow"
                    ),
                ),
                (
                    "intent_analysis",
                    models.JSONField(
                        default=dict, help_text="AI analysis of user intent"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="ai_tool_recommender.conversationsession",
                    ),
                ),
            ],
            options={
                "db_table": "chat_messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="RefineQuerySession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "original_prompt",
                    models.TextField(help_text="User's initial high-level request"),
                ),
                (
                    "refined_query",
                    models.TextField(
                        blank=True, help_text="Refined query after AI processing"
                    ),
                ),
                (
                    "refinement_history",
                    models.JSONField(
                        default=list,
                        help_text="History of query refinements and AI suggestions",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Refinement"),
                            ("refining", "Being Refined"),
                            ("refined", "Query Refined"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Current status of the refinement session",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refine_query_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "refine_query_sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="conversationsession",
            index=models.Index(
                fields=["user", "created_at"], name="conversatio_user_id_aff77d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationsession",
            index=models.Index(
                fields=["session_id"], name="conversatio_session_376463_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationsession",
            index=models.Index(
                fields=["is_active", "updated_at"],
                name="conversatio_is_acti_e717cf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["session", "created_at"], name="chat_messag_session_597c4e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["message_type", "created_at"],
                name="chat_messag_message_977880_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="refinequerysession",
            index=models.Index(
                fields=["user", "created_at"], name="refine_quer_user_id_a98ca3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="refinequerysession",
            index=models.Index(
                fields=["session_id"], name="refine_quer_session_606206_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="refinequerysession",
            index=models.Index(
                fields=["status", "created_at"], name="refine_quer_status_1cd646_idx"
            ),
        ),
    ]
