# Generated by Django 5.2.7 on 2025-10-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ai_tool_recommender",
            "0003_conversationsession_chatmessage_refinequerysession_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationsession",
            name="refined_query",
            field=models.TextField(
                blank=True, help_text="AI-refined version of the original query"
            ),
        ),
    ]
