# Generated by Django 5.1.6 on 2025-10-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_tool_recommender', '0004_conversationsession_refined_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationsession',
            name='current_question_index',
            field=models.IntegerField(default=0, help_text='Index of the current question being asked'),
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='questionnaire_json',
            field=models.JSONField(blank=True, default=dict, help_text='Questionnaire with questions and answers', null=True),
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='total_questions',
            field=models.IntegerField(default=0, help_text='Total number of questions in the questionnaire'),
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='workflow_state',
            field=models.CharField(choices=[('initial', 'Initial'), ('questioning', 'Asking Questions'), ('generating_workflow', 'Generating Workflow'), ('workflow_ready', 'Workflow Ready'), ('error', 'Error')], default='initial', help_text='Current state of the workflow generation process', max_length=30),
        ),
    ]
