# Generated by Django 5.2.7 on 2025-10-27 15:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_tool_recommender", "0005_add_questionnaire_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RefinedQuery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "workflow_id",
                    models.UUIDField(db_index=True, help_text="Associated workflow ID"),
                ),
                ("original_query", models.TextField(help_text="Original user query")),
                (
                    "refined_query",
                    models.TextField(help_text="AI-refined query from Phase 3"),
                ),
                (
                    "workflow_info",
                    models.JSONField(
                        default=dict,
                        help_text="Complete workflow information (intent, outcome, tools, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refined_queries",
                        to="ai_tool_recommender.conversationsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refined_queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "refined_queries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["workflow_id"], name="refined_que_workflo_7746ad_idx"
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="refined_que_user_id_a9755a_idx",
                    ),
                    models.Index(
                        fields=["session"], name="refined_que_session_a70e69_idx"
                    ),
                ],
            },
        ),
    ]
