# Generated by Django 5.2.7 on 2025-11-26 14:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_tool_recommender", "0006_refinedquery"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowImplementationGuide",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "workflow_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="ID of the associated workflow (from either Workflow or WorkflowGeneration model)",
                    ),
                ),
                (
                    "implementation_guide",
                    models.TextField(
                        help_text="Complete step-by-step implementation guide in Markdown format"
                    ),
                ),
                (
                    "workflow_snapshot",
                    models.JSONField(
                        default=dict,
                        help_text="Snapshot of workflow data when implementation was generated",
                    ),
                ),
                (
                    "tools_count",
                    models.IntegerField(
                        default=0, help_text="Number of tools in the workflow"
                    ),
                ),
                ("generation_time_ms", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generating", "Generating"),
                            ("completed", "Completed"),
                            ("error", "Error"),
                        ],
                        default="generating",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_implementations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "workflow_implementation_guides",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["workflow_id"], name="workflow_im_workflo_311f56_idx"
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="workflow_im_user_id_0c0617_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="workflow_im_status_a04d7b_idx",
                    ),
                ],
                "unique_together": {("user", "workflow_id")},
            },
        ),
    ]
