# Generated by Django 5.2.7 on 2025-12-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_tool_recommender", "0007_workflowimplementationguide"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="agent_name",
            field=models.CharField(
                choices=[
                    ("refine_query_generator", "Refine Query Generator"),
                    ("workflow_builder", "Workflow Builder"),
                    ("general_assistant", "General Assistant"),
                    ("implementation_chat", "Implementation Chat"),
                    ("tool_assistant", "Tool Assistant"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                help_text="Name of the agent that generated this response",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="user_responded_to_agent",
            field=models.CharField(
                blank=True,
                help_text="Name of the agent the user was responding to",
                max_length=50,
            ),
        ),
    ]
