# Generated by Django 5.1.6 on 2025-03-25 12:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=100)),
                ("features", models.TextField()),
                ("tags", models.CharField(max_length=500)),
                ("website", models.CharField(blank=True, max_length=255)),
                ("twitter", models.CharField(blank=True, max_length=255)),
                ("facebook", models.CharField(blank=True, max_length=255)),
                ("linkedin", models.CharField(blank=True, max_length=255)),
                ("tiktok", models.CharField(blank=True, max_length=255)),
                ("youtube", models.CharField(blank=True, max_length=255)),
                ("instagram", models.CharField(blank=True, max_length=255)),
                ("price_from", models.CharField(max_length=50)),
                ("price_to", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
