# Generated by Django 5.2.7 on 2025-10-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Consultant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("expertise", models.TextField(blank=True, null=True)),
                ("experience", models.TextField(blank=True, null=True)),
                ("website", models.URLField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("gmail", models.EmailField(blank=True, max_length=254, null=True)),
                ("apps_included", models.TextField(blank=True, null=True)),
                ("language", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("type_of_services", models.TextField(blank=True, null=True)),
                (
                    "countries_with_office_locations",
                    models.TextField(blank=True, null=True),
                ),
                ("about", models.TextField(blank=True, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("time", models.TimeField(blank=True, null=True)),
                ("embedding", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "consultants",
            },
        ),
    ]
