# Generated by Django 5.1.6 on 2025-03-11 16:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InviteFriendsForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emails",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.EmailField(max_length=254),
                        help_text="Enter up to 3 email addresses of friends you'd like to invite",
                        size=None,
                        verbose_name="Friend's Emails",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Invite Friends Form",
                "verbose_name_plural": "Invite Friends Forms",
                "ordering": ["-created_at"],
            },
        ),
    ]
