# Generated by Django 5.2.7 on 2025-11-28 09:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScrapingJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[("CSV_UPLOAD", "CSV Upload")],
                        default="CSV_UPLOAD",
                        max_length=50,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True, default=dict, help_text="Arbitrary job data"
                    ),
                ),
                ("file", models.FileField(upload_to="csv_uploads/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("logs", models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name="ToolSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "csv_row_nr",
                    models.IntegerField(help_text="Row number in the original CSV"),
                ),
                (
                    "website",
                    models.URLField(help_text="Primary website URL", max_length=2000),
                ),
                ("title", models.CharField(blank=True, max_length=500)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(blank=True, max_length=255)),
                ("master_category", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("INVALID", "Invalid URL"),
                            ("QUEUED", "Queued for Scraping"),
                            ("SCRAPED", "Scraped"),
                            ("PROCESSED", "Processed"),
                            ("INDEXED", "Indexed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("raw_html", models.TextField(blank=True, null=True)),
                ("clean_html", models.TextField(blank=True, null=True)),
                (
                    "fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="All extracted metadata fields",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sites",
                        to="tool_scraping.scrapingjob",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CombinedText",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "combined_text",
                    models.TextField(help_text="Combined text from all site pages"),
                ),
                ("char_count", models.IntegerField(help_text="Total character count")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="combined_text_record",
                        to="tool_scraping.toolsite",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SitePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=2000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SCRAPED", "Scraped"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("raw_html", models.TextField(blank=True, null=True)),
                ("clean_html", models.TextField(blank=True, null=True)),
                ("page_text", models.TextField(blank=True, null=True)),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
                ("scraped_at", models.DateTimeField(blank=True, null=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="tool_scraping.toolsite",
                    ),
                ),
            ],
            options={
                "unique_together": {("site", "url")},
            },
        ),
    ]
