# Generated by Django 5.2.7 on 2025-11-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tool_scraping", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scrapingjob",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="csv_uploads/"),
        ),
        migrations.AlterField(
            model_name="scrapingjob",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("CSV_UPLOAD", "CSV Upload"),
                    ("INTERNET_DISCOVERY", "Internet Discovery"),
                ],
                default="CSV_UPLOAD",
                max_length=50,
            ),
        ),
    ]
