# Generated by Django 5.1.6 on 2025-10-03 12:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsultantSearchLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("query", models.TextField(help_text="Search query for consultants")),
                (
                    "user_work_description",
                    models.TextField(
                        blank=True, help_text="Description of user's work/project"
                    ),
                ),
                ("results_count", models.IntegerField(default=0)),
                ("top_score", models.FloatField(blank=True, null=True)),
                ("response_time_ms", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("error", "Error"),
                            ("no_results", "No Results"),
                        ],
                        default="success",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultant_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "consultant_search_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsultantRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "consultant_external_id",
                    models.CharField(
                        blank=True,
                        help_text="External consultant ID from Pinecone",
                        max_length=100,
                    ),
                ),
                ("relevance_score", models.FloatField()),
                (
                    "rank",
                    models.IntegerField(help_text="Position in recommendation list"),
                ),
                ("viewed", models.BooleanField(default=False)),
                ("clicked", models.BooleanField(default=False)),
                ("contacted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("viewed_at", models.DateTimeField(blank=True, null=True)),
                ("clicked_at", models.DateTimeField(blank=True, null=True)),
                ("contacted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "contractor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations_as_contractor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "search_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="consultant_recommender.consultantsearchlog",
                    ),
                ),
            ],
            options={
                "db_table": "consultant_recommendations",
                "ordering": ["search_log", "rank"],
            },
        ),
        migrations.CreateModel(
            name="MeetingRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("client_name", models.CharField(max_length=255)),
                ("client_email", models.EmailField(max_length=254)),
                ("company_name", models.CharField(blank=True, max_length=255)),
                (
                    "contractor_id_external",
                    models.CharField(
                        blank=True,
                        help_text="External contractor ID if not a system user",
                        max_length=100,
                    ),
                ),
                ("contractor_name", models.CharField(max_length=255)),
                ("contractor_email", models.EmailField(max_length=254)),
                ("preferred_date", models.DateField()),
                ("preferred_time", models.TimeField()),
                ("project_description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("client_notes", models.TextField(blank=True)),
                ("contractor_notes", models.TextField(blank=True)),
                ("admin_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contractor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contractor_meetings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "meeting_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="consultantsearchlog",
            index=models.Index(
                fields=["user", "created_at"], name="consultant__user_id_6a2a2f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consultantsearchlog",
            index=models.Index(
                fields=["status", "created_at"], name="consultant__status_2857a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consultantrecommendation",
            index=models.Index(
                fields=["search_log", "rank"], name="consultant__search__7f5fb5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consultantrecommendation",
            index=models.Index(
                fields=["contractor_user", "created_at"],
                name="consultant__contrac_37017b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="meetingrequest",
            index=models.Index(
                fields=["client", "status"], name="meeting_req_client__9bcac1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meetingrequest",
            index=models.Index(
                fields=["contractor", "status"], name="meeting_req_contrac_3dd16e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meetingrequest",
            index=models.Index(
                fields=["status", "preferred_date"],
                name="meeting_req_status_db9ebc_idx",
            ),
        ),
    ]
