# Generated by Django 5.2.7 on 2025-12-03 10:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultant_recommender", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowConsultants",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "workflow_id",
                    models.CharField(
                        db_index=True,
                        help_text="ID of the workflow these consultants are cached for",
                        max_length=36,
                    ),
                ),
                (
                    "query",
                    models.TextField(help_text="Search query used to find consultants"),
                ),
                (
                    "user_work_description",
                    models.TextField(
                        blank=True, help_text="User work description used in search"
                    ),
                ),
                (
                    "consultants_data",
                    models.JSONField(
                        help_text="JSON array of consultant objects with all their details"
                    ),
                ),
                ("consultants_count", models.IntegerField(default=0)),
                (
                    "search_metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Additional metadata from the search (total_found, response_time, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this workflow consultant cache",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_consultants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "workflow_consultants",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["workflow_id", "user"],
                        name="workflow_co_workflo_162e6b_idx",
                    ),
                    models.Index(
                        fields=["user", "updated_at"],
                        name="workflow_co_user_id_558a1d_idx",
                    ),
                ],
                "unique_together": {("workflow_id", "user")},
            },
        ),
    ]
